//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.12 at 01:31:13 AM EEST 
//


package org.zisist.model.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for leaderboard_configuration complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="leaderboard_configuration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="leaderboards" type="{}leaderboards"/>
 *         &lt;element name="merger" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="publisher" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "leaderboard_configuration", propOrder = {
    "description",
    "leaderboards",
    "merger",
    "publisher"
})
@XmlRootElement(name = "leaderboard_configuration")
public class LeaderboardConfiguration {

    @XmlElement(required = true)
    protected String description;
    @XmlElement(required = true)
    protected Leaderboards leaderboards;
    @XmlElement(required = true)
    protected String merger;
    @XmlElement(required = true)
    protected String publisher;
    @XmlAttribute
    protected String name;

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the leaderboards property.
     * 
     * @return
     *     possible object is
     *     {@link Leaderboards }
     *     
     */
    public Leaderboards getLeaderboards() {
        return leaderboards;
    }

    /**
     * Sets the value of the leaderboards property.
     * 
     * @param value
     *     allowed object is
     *     {@link Leaderboards }
     *     
     */
    public void setLeaderboards(Leaderboards value) {
        this.leaderboards = value;
    }

    /**
     * Gets the value of the merger property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMerger() {
        return merger;
    }

    /**
     * Sets the value of the merger property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMerger(String value) {
        this.merger = value;
    }

    /**
     * Gets the value of the publisher property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPublisher() {
        return publisher;
    }

    /**
     * Sets the value of the publisher property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPublisher(String value) {
        this.publisher = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

}
