//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.12 at 01:31:13 AM EEST 
//


package org.zisist.model.xml;

import javax.xml.bind.annotation.*;


/**
 * <p>Java class for leaderboard complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="leaderboard">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="input_uri" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="input_analyzer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "leaderboard", propOrder = {
    "inputUri",
    "inputAnalyzer"
})
@XmlRootElement(name = "leaderboard")
public class Leaderboard {

    @XmlElement(name = "input_uri", required = true)
    protected String inputUri;
    @XmlElement(name = "input_analyzer", required = true)
    protected String inputAnalyzer;

    /**
     * Gets the value of the inputUri property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputUri() {
        return inputUri;
    }

    /**
     * Sets the value of the inputUri property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputUri(String value) {
        this.inputUri = value;
    }

    /**
     * Gets the value of the inputAnalyzer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getInputAnalyzer() {
        return inputAnalyzer;
    }

    /**
     * Sets the value of the inputAnalyzer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setInputAnalyzer(String value) {
        this.inputAnalyzer = value;
    }

}
