//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.10.12 at 01:31:13 AM EEST 
//


package org.zisist.model.xml;

import javax.xml.bind.annotation.*;
import java.util.ArrayList;
import java.util.List;


/**
 * <p>Java class for leaderboard_configurations complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="leaderboard_configurations">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="leaderboard_configuration" type="{}leaderboard_configuration" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "leaderboard_configurations", propOrder = {
    "leaderboardConfiguration"
})
@XmlRootElement(name = "leaderboard_configurations")
public class LeaderboardConfigurations {

    @XmlElement(name = "leaderboard_configuration", required = true)
    protected List<LeaderboardConfiguration> leaderboardConfiguration;

    /**
     * Gets the value of the leaderboardConfiguration property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the leaderboardConfiguration property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLeaderboardConfiguration().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LeaderboardConfiguration }
     * 
     * 
     */
    public List<LeaderboardConfiguration> getLeaderboardConfiguration() {
        if (leaderboardConfiguration == null) {
            leaderboardConfiguration = new ArrayList<LeaderboardConfiguration>();
        }
        return this.leaderboardConfiguration;
    }

}
